Azure/co-op-translator

.gitattributes
This PR addresses the issue of large file sizes in Jupyter Notebooks due to the inclusion of numerous example images. These large `.ipynb` files are significantly affecting the language statistics of the repository, causing Jupyter Notebook to be displayed as the primary language, which may not accurately reflect the project's main focus.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: Add .gitattributes file 
```
=> Add .gitattributes file with  Jupyter Notebooks configuration

src/co_op_translator/translators/markdown_translator.py, src/co_op_translator/utils/markdown_utils.py
During markdown translation, code blocks and inline code were sometimes split across multiple chunks, causing errors or incomplete translations. This often led to broken translations, especially for longer documents with numerous code snippets. Additionally, in some cases, inline code and code blocks contained variables or syntax that could cause errors in the Semantic Kernel translation process.
- Implemented a process to replace code blocks (` ``` `) and inline code (` `` `) with placeholders like `@@CODE_BLOCK_x@@` and `@@INLINE_CODE_x@@` before sending the document for translation.
- After the translation is completed, the placeholders are replaced back with the original code blocks and inline code.
- This ensures that code blocks and inline code are not split between chunks, leading …
```
=> Fix issue with markdown translation where code blocks were split across chunks

src/co_op_translator/__main__.py, src/co_op_translator/config/base_config.py, src/co_op_translator/config/font_config.py, src/co_op_translator/translators/image_translator.py, src/co_op_translator/translators/markdown_translator.py, src/co_op_translator/translators/project_translator.py, src/co_op_translator/translators/text_translator.py, tests/co_op_translator/config/test_base_config.py, tests/co_op_translator/config/test_font_config.py
The primary goal of this change is to refactor the Config class, replacing the old constant-based configuration access with static methods. This refactor helps improve encapsulation and allows for better testability and flexibility in how configuration values are retrieved. This change affects how Azure-related keys (e.g., AZURE_SUBSCRIPTION_KEY, AZURE_OPENAI_API_KEY, etc.) are accessed throughout the translation logic.
This PR also includes added tests related to config to ensure the refactor does not break existing functionality.
I've added test for config, and refactor the Config class, replacing the old constant-based configuration access with static methods
If you're not sure, try …
=> Translator: Refactor Config class to use static methods for configuration access and add tests for config

.github/workflows/label-title-prefix.yml, .github/workflows/labeler-pr.yml
I've added two GitHub Actions: one for labeling pull requests based on file changes, and another for automatically adding a title prefix to issues or PRs based on the label applied.
- Added a GitHub Action for labeling pull requests based on modified paths (labeler-pr.yml).
- Added a GitHub Action for automatically adding a title prefix to issues or pull requests when specific labels are applied (label-title-prefix.yml).
- The title prefixes are dynamically generated based on the applied label (e.g., "Docs", "Build", "Translator").
No related issues.
These new GitHub …
=> Add GitHub Actions for PR labeling and automatic title prefixing

CONTRIBUTING.md
This PR updates the `CONTRIBUTING.md` to modify the virtual environment setup, changing the environment name from `venv` to `.venv` for consistency with the project setup guidelines. Additionally, a maintainer guide section has been added to provide clarity on the commit message format and merge strategy, especially for the final squash and merge commits.
- Updated references to the virtual environment name from `venv` to `.venv` throughout the documentation for consistency.
- Added a new section under **Maintainers** in `CONTRIBUTING.md`, which outlines the **Commit message format** and **Merge strategy** used in the project.
- Included a note explaining that prefixes (`Docs`, `Translator`, `Build`) are automatically generated based on labels, so contributors need only verify correctness …
=> Docs: Update virtual environment name and add maintainer guide to CONTRIBUTING.md

tests/co_op_translator/translators/test_image_translator.py
Add unit tests for the `ImageTranslator` class to verify the correct functionality of text extraction, translation, and image annotation.
- Added unit tests for key methods of `ImageTranslator`:
- `extract_line_bounding_boxes`
- `translate_image`
- Mocked necessary dependencies such as `Image.open` and Azure Image Analysis client to simulate image processing and text extraction.
- Verified the behavior of bounding box extraction, text translation, and image annotation to ensure the process is functioning as expected.
=> Translator: Add unit tests for Image_translator

src/co_op_translator/utils/image_utils.py, tests/co_op_translator/translators/test_image_translator.py, tests/co_op_translator/utils/test_image_utils.py
1. The draw_text_on_image function had a bug where the size of the text was incorrectly handled as a list instead of a tuple. This has been corrected to ensure proper functionality.
2. Several improvements were made to the test cases for test_image_translator to ensure proper testing of bounding box extraction and image translation.
3. Added tests for image_utils.py
=> Fix tuple conversion in draw_text_on_image function, improve test_image_translator ,and add tests for image_utils.py

tests/co_op_translator/translators/test_image_translator.py, tests/co_op_translator/translators/test_markdown_translator.py
- This update refactors `test_image_translator` to use a temporary path instead of a real file path, which improves test reliability by isolating test output. 
- Added new tests for `markdown_translator` 
- Updated `ImageTranslator` tests to utilize `tmp_path` fixture for temporary directories in place of hardcoded paths.
- Enhanced `test_translate_image` to assert the correct temporary path for translated images, improving isolation and ensuring that temporary data is used during test execution.
- Added new tests for `markdown_translator`.
=> Translator: Improve test_image_translator to use temp_path instead of real path and add tests for markdown translator

README.md, src/co_op_translator/translators/project_translator.py
This PR addresses an issue in the translation retry process within the `check_and_retry_translations` method. It aims to prevent infinite loop scenarios by ensuring only specific language-file pairs are retried if translation errors are detected.
This change refines the translation retry logic to handle only mismatched files for specific language codes
- Storing both file path and language code in the mismatched_files list, allowing precise retries for the affected language-file pairs
- Removing the unnecessary nested loop during the retry phase to eliminate redundant translations and potential infinite loops
- Simplifying the collection of markdown files by generating all language-file combinations at once, improving efficiency
When developers merge from main and run the server, azd up, …
=> Translator: Fix bug in translation retry process, improve language-specific handling and efficiency

.github/labeler.yml, .github/workflows/label-title-prefix.yml, CONTRIBUTING.md
This pull request updates the `CONTRIBUTING.md` file and associated configuration files to align with the updated prefix convention for commits and labels. Specifically, it replaces the `Translator` prefix with `Core` for changes affecting the core functionality of the project.
- Updated the `CONTRIBUTING.md` to reflect the updated prefix convention for commits.
- Modified `.github/labeler.yml` to apply the `Core` label for changes in `src/co_op_translator/**/*`.
- Adjusted `.github/workflows/label-title-prefix.yml` to use the `Core` prefix for commits instead of `Translator`.
Fixes #33
Before submitting your pull request, please …
=> Build, Docs: Update CONTRIBUTING.md and configuration files to align with new prefix convention

src/co_op_translator/config/llm_config/azure_openai.py, src/co_op_translator/config/llm_config/openai.py
Bug fix - configuring LLM
I was getting ValueError: No LLM service properly configured
**solution:** added the following to the config file:
from dotenv import load_dotenv
load_dotenv()
none
error details
=> updating LLM configuration to get details from dotenv file

src/co_op_translator/__main__.py, src/co_op_translator/config/llm_config/azure_openai.py, src/co_op_translator/config/llm_config/openai.py, src/co_op_translator/core/project/directory_manager.py, src/co_op_translator/core/project/translation_manager.py, tests/co_op_translator/core/project/test_project_translator.py
Fix a bug where orphaned translation files were not being deleted when their original files were renamed. This was caused by a JSON parsing error in the metadata handling code.
When an original file (e.g., README.md) was renamed, its corresponding translation files should have been deleted as they became orphaned. However, due to a JSON parsing error when handling the `CO_OP_TRANSLATOR_METADATA` prefix in translation files, these orphaned files were not being properly identified and deleted.
The fix modifies the metadata parsing logic to correctly handle the prefix, allowing the orphaned file cleanup process to work as intended. …
=> Core: Fix orphaned translation files not being deleted when original files are renamed

getting_started/supported-languages.md, src/co_op_translator/fonts/font_language_mappings.yml
Adds support for Brazilian Portuguese (br) as a distinct locale and clarifies the current behavior of `pt` mapping to Portuguese (Portugal).
Fixes #97 
=> Clarify `pt` Mapping to `pt-PT` and Support Brazilian Portuguese `br` Locale

README.md, pyproject.toml, src/co_op_translator/utils/common/file_utils.py, src/co_op_translator/utils/llm/markdown_utils.py, tests/co_op_translator/utils/llm/test_markdown_utils.py
The purpose of this PR is to fix an issue with how paths starting with '/' (root-relative paths) are handled in the co-op-translator. Previously, these paths were not correctly processed in both markdown-only mode and regular (non-markdown-only) mode, leading to broken image links in translated documents.
The changes modify how root-relative paths are processed in both translation modes:
1. In markdown-only mode: paths starting with '/' are now kept unchanged (instead of being converted to relative paths)
In non-markdown-only mode: paths starting with '/' are correctly resolved from the project root and properly linked to translated images
2. The get_actual_image_path function was enhanced with a root_dir parameter to properly resolve root-relative paths
Test cases were added to verify …
=> Core: Improve handling of root-relative paths in all translation modes

src/co_op_translator/utils/common/file_utils.py, tests/co_op_translator/utils/common/test_file_utils.py
Ensure consistent hash generation across different operating systems by normalizing file path separators. This prevents platform-specific discrepancies in `get_unique_id`.
- Updated `get_unique_id` to normalize path separators to `'/'` before hashing.
- Ensures consistent SHA-256 hashes regardless of whether input paths use `\` (Windows) or `/` (Unix).
- Added a new test `test_cross_platform_path_hash_consistency` to validate hash stability across OS-specific path formats.
#128 
This resolves an edge case where identical file structures on Windows and Unix could result in different translation cache keys due to differing path separator styles. This is especially important for consistent …
=> Fix image filename hash inconsistency by normalizing path separators across OS

src/co_op_translator/cli/translate.py, src/co_op_translator/core/llm/jupyter_notebook_translator.py, src/co_op_translator/core/llm/markdown_translator.py, src/co_op_translator/core/project/project_translator.py, src/co_op_translator/core/project/translation_manager.py, src/co_op_translator/utils/common/file_utils.py, tests/co_op_translator/core/llm/test_jupyter_notebook_translator.py, tests/co_op_translator/core/project/test_jupyter_notebook_integration.py, tests/co_op_translator/core/project/test_project_translator.py
Add support for selective translation of Jupyter notebook files through a new CLI option, allowing users to translate only notebook files when needed instead of processing all file types.
This PR introduces a new --notebook/-n CLI option that enables users to translate only Jupyter notebook files (.ipynb). This complements the existing --markdown and --images options, providing more granular control over translation workflows.
- CLI Enhancement: Added --notebook/-n flag to the translate command
- Improved Logic: Enhanced translation mode determination to handle notebook-only translation
- Updated Pipeline: Modified ProjectTranslator and TranslationManager to support selective notebook translation
- Better UX: Updated help text and usage examples to include notebook translation scenarios …
=> Core: Add CLI option for selective notebook file translation (-n/--notebook)

getting_started/command-line-guide/install-package.md
* Typo "![NOTE]"→"> [!NOTE]"
* https://github.com/Azure/co-op-translator/blob/main/getting_started/command-line-guide/install-package.md
=> Update install-package.md (Typo "![NOTE]"→"> [!NOTE]")

src/co_op_translator/core/llm/text_translator.py, src/co_op_translator/utils/llm/text_utils.py, tests/co_op_translator/core/llm/test_jupyter_notebook_translator.py, tests/co_op_translator/core/llm/test_markdown_evaluator.py, tests/co_op_translator/core/llm/test_text_translator.py, tests/co_op_translator/core/project/test_translation_manager.py, tests/co_op_translator/core/vision/test_image_translator.py, tests/co_op_translator/utils/common/test_metadata_utils.py, tests/co_op_translator/utils/llm/test_text_utils.py
Fix critical translation issues by implementing OpenAI structured outputs to ensure accurate text positioning and eliminate output inconsistencies. This addresses Arabic ligature rendering problems and Korean translation duplication issues that were caused by inconsistent line count mapping between input and output text.
This PR replaces the existing YAML-based translation approach with OpenAI's structured outputs feature, which guarantees exact 1:1 line mapping between source and translated text. The previous implementation relied on manual YAML parsing that sometimes resulted in mismatched line counts, causing:
- Arabic ligature issues (#123): Text positioned incorrectly due to line count mismatches
- Korean translation duplication (#204): Both English and Korean text appearing in …
=> Core: Implement structured outputs to resolve translation issues

src/co_op_translator/utils/llm/text_utils.py, tests/co_op_translator/utils/llm/test_text_utils.py
- Remove automatic line numbering (1., 2., etc.) from gen_image_translation_prompt
- Add "preserve original formatting" instruction to translation prompt
- Ensures translated text maintains original format without added numbers
- Fixes issue where images without numbering were getting numbered translations
=> Remove unwanted numbering from image translation prompts

getting_started/command-reference.md, pyproject.toml, src/co_op_translator/__main__.py, src/co_op_translator/cli/migrate_links.py, src/co_op_translator/utils/common/file_utils.py, src/co_op_translator/utils/llm/markdown_utils.py, tests/co_op_translator/utils/common/test_file_utils.py, tests/co_op_translator/utils/llm/test_markdown_utils.py, tests/co_op_translator/utils/llm/test_text_utils.py
- Add a CLI to migrate .ipynb links in translated Markdown to their translated notebooks.
- Align logging behavior with translate command for consistent UX.
- Document the new command in the command reference.
- CLI:
- Added `migrate-links` in [src/co_op_translator/cli/migrate_links.py](cci:7://file:///c:/Users/sms79/dev/co-op-translator/src/co_op_translator/cli/migrate_links.py:0:0-0:0).
- Scans translated Markdown under `translations/<lang>/...` and updates `.ipynb` links:
- Prefer translated notebooks if present.
- Otherwise, optionally fall back to original notebooks via `--fallback-to-original` (default: on).
- Options:
- `-l/--language-codes`
- `-r/--root-dir`
- `--dry-run`
- `--fallback-to-original/--no-fallback-to-original`
- `-d/--debug` (DEBUG when set; CRITICAL by default)
- …
=> Add migrate-links command

src/co_op_translator/core/llm/markdown_translator.py
This PR resolves issue #209 by adding a separator line before the "Disclaimer" text for better readability.
A separator (`---`) has been added to visually distinguish the disclaimer section from the content above it.
Fixes #209
N/A
=> Resolved #209: Add a separator line before the "Disclaimer" text.

src/co_op_translator/cli/translate.py, src/co_op_translator/config/llm_config/config.py, src/co_op_translator/config/vision_config/config.py
- Fail fast with actionable feedback by validating connectivity/credentials for both LLM and Vision services at startup.
- Improve readability by removing redundant try/except blocks in the CLI.
- Feature: LLM connectivity validation
- File: [src/co_op_translator/config/llm_config/config.py](cci:7://file:///c:/Users/sms79/dev/co-op-translator/src/co_op_translator/config/llm_config/config.py:0:0-0:0)
- Added [LLMConfig.validate_connectivity()](cci:1://file:///c:/Users/sms79/dev/co-op-translator/src/co_op_translator/config/vision_config/config.py:81:4-123:18):
- Azure OpenAI: Performs a minimal chat completions POST to validate endpoint, api-version, API key, and deployment. Hard-fails on 401/403, warns and proceeds on others.
- OpenAI: Performs a minimal chat completion using SDK. …
=> Add LLM/Vision Connectivity Health Checks and Simplify CLI Flow

getting_started/command-reference.md, src/co_op_translator/cli/evaluate.py, src/co_op_translator/cli/migrate_links.py, src/co_op_translator/cli/translate.py, src/co_op_translator/utils/common/logging_utils.py
Add a reusable, cross-platform logging capability to the CLI that allows users to persist DEBUG-level logs to files with a simple flag.
This change introduces a shared logging utility and wires a new `--save-logs` flag (with short form `-s`) into all CLI commands. When enabled, logs are written to files under the project’s `--root-dir` at DEBUG level, while console verbosity remains controlled by `-d`.
- Introduce reusable logging utility: [src/co_op_translator/utils/common/logging_utils.py](cci:7://file:///c:/Users/sms79/dev/co-op-translator/src/co_op_translator/utils/common/logging_utils.py:0:0-0:0)
- [setup_logging(root_dir, debug, save_logs, command_name)](cci:1://file:///c:/Users/sms79/dev/co-op-translator/src/co_op_translator/utils/common/logging_utils.py:35:0-96:24)
- Console: …
=> Add --save-logs (-s) to persist DEBUG logs to files

src/co_op_translator/core/llm/markdown_translator.py, src/co_op_translator/utils/llm/markdown_utils.py
Improve translation reliability for disclaimers and ensure correct handling of inline HTML `<img>` tags inside Markdown files.  
This solves broken image paths and ensures that the disclaimer message is consistently generated and translated across languages.
- **markdown_translator.py**
- Refactored `generate_disclaimer` to use `system_text` + `user_text` format with `SPLIT_DELIMITER` for more predictable prompt structure.
- Updated disclaimer text to be clearly formatted with line breaks and consistent Markdown syntax.
- **markdown_utils.py**
- Added HTML `<img>` tag support to `update_image_links` to preserve tag attributes while rewriting `src` paths.
- Enhanced prompt template rules to explicitly instruct preserving inline HTML tags.
These changes prevent accidental modification of …
=> Core: Support HTML <img> links in markdown and fix disclaimer prompt split
