- .gitignore
- pyproject.toml
I've updated it to exclude additional environment directories (`.env`, `.venv`, etc.) and generated output files like `dist`, .`idea/`, and `.pytest_cache`. I've bumped the version from `0.2.0` to `0.2.1`.
> Update .gitignore and bump version to 0.2.1 in pyproject.toml

- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .github/ISSUES_TEMPLATE.MD
- .github/PULL_REQUEST_TEMPLATE.MD
- README.md
- requirements.txt
Adding DevContainer Environment
> Add Devcontainer

- README.md
This PR enhances the README by including a comprehensive table that lists the currently supported languages, their language codes, and any known issues for each language. This table will help users understand which languages are supported by **Co Op Translator** and provide a clear reference for contributors who wish to add support for new languages.
1. Added a `Supported Languages` section to the README.
2. Included a table with language codes, language names, font information, RTL support, and known issues.
3. Provided instructions on how to add support for new languages, including guidance on verifying font licenses.
```
[ ] Yes
[x …
```
> Add Supported Languages Table to README

- CONTRIBUTING.md
- README.md
Update README.md and Add CONTRIBUTING.md
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```
> Update README.md and Add CONTRIBUTING.md

- .github/labeler.yml
I've added a **labeler.yml** file to automate the process of applying labels to pull requests and issues based on file changes. The labeler will assign appropriate labels for changes related to documentation, tests, build configurations, and source code.
> Build: Add labeler.yml for automatic labeling

- .github/workflows/label-title-prefix.yml
> Build: Fix title prefix

- README.md
- getting_started/Phi-3Cookbook-translation-case.md
This PR adds a new section titled **"Why choose Co-op Translator for Markdown translations?"** to the README, which explains the advantages of using Co-op Translator for translating Markdown files. It also updates the **Phi-3 Cookbook translation case study** with details on how translated README links are automatically adjusted during the translation process, allowing seamless navigation between different language versions.
These changes enhance the documentation by providing more context on the key features of Co-op Translator, particularly regarding Markdown translation. The added information aims to clarify how the tool preserves Markdown syntax and automatically adjusts translation links, improving user experience.
None.
When developers merge from main and run the server, azd up, or …
> Docs: Add 'Why Choose Co-op Translator for Markdown Translations?' section and update Phi-3 Cookbook case study in README

- README.md
> Docs: Update title

- tests/co_op_translator/translators/test_image_translator.py
- tests/co_op_translator/translators/test_text_translator.py
- tests/co_op_translator/utils/test_image_utils.py
I've added tests for `text_translator` to validate the functionality of translation methods within the `TextTranslator` class. I've also included a refactor of existing test files to improve coverage.
- Added tests for `translate_image_text` and `translate_text` methods in `text_translator`.
- Refactored several test files to remove redundant lines and improve readability.
- Updated test cases for the `image_translator` and `image_utils` modules, including minor changes in assertions and setup.
This refactor and test addition enhance the maintainability and accuracy of tests by organizing them into more structured files with relevant mocks and assertions.
N/A
When developers merge from `main` and run the server, `azd up`, or `azd deploy`, will this produce an error?
Before submitting your …
> Translator: Add tests for text_translator and Refactor test files for better coverage

- pyproject.toml
> Build: Release version 0.5.1

- pyproject.toml
- src/co_op_translator/__main__.py
- src/co_op_translator/config/base_config.py
> Ensure .env loading from project root directory

- pyproject.toml
- src/co_op_translator/__main__.py
- src/co_op_translator/config/base_config.py
> Fix: ensure .env loading from project root directory

- getting_started/set-up-resources/set-up-azure-computer-vision.md
- getting_started/set-up-resources/set-up-azure-openai.md
> Docs: Fix broken links

- pyproject.toml
> Build: Release version 0.6.3

- README.md
- getting_started/troubleshooting.md
Added troubleshooting guide for markdown tag checking and image url validation
Added troublshooting.md and updated readme to link to troubleshooting guide
None this was a missing detail for confirming with users to validate content after translation.
> Docs: Add troubleshooting guide

- pyproject.toml
> Build: Update version to 0.7.2b1

- README.md
Fixed typos in README.md
Corrected minor spelling errors
> Docs: Improve readability for README.md

- README.md
> Delete unused headline

- src/co_op_translator/core/llm/markdown_translator.py
> Core: Update disclaimer to include the Co-op Translator link

- pyproject.toml
> Build: Update version to v0.8.0-test

- pyproject.toml
> Build: Update version to 0.8.0.dev0

- README.md
> Docs: Showcase official Microsoft repos using Co-op Translator

- pyproject.toml
- src/co_op_translator/core/project/directory_manager.py
- src/co_op_translator/utils/common/metadata_utils.py
- tests/co_op_translator/core/project/test_directory_manager.py
- tests/co_op_translator/utils/common/test_metadata_utils.py
This PR addresses cross-platform path handling issues between Windows and Linux environments, ensuring that file paths in translation metadata are consistently normalized regardless of the operating system. This fixes orphaned file cleanup and translation update functionality when running on different platforms.
The co-op-translator project was experiencing issues when running on Linux (e.g., GitHub Actions) with metadata created on Windows, as Windows-style backslash paths weren't being properly resolved. This PR implements consistent path normalization using forward slashes (POSIX style) in all metadata, making the application fully cross-platform compatible.
Fixes #111 
If you're not …
> Core: Normalize path separators for cross-platform compatibility

- getting_started/github-actions-guide/github-actions-guide-org.md
- getting_started/github-actions-guide/github-actions-guide-public.md
> Update GitHub action guides

- README.md
- getting_started/command-line-guide/command-line-guide.md
- getting_started/set-up-azure-ai.md
- src/co_op_translator/core/llm/markdown_translator.py
- src/co_op_translator/core/llm/providers/azure/markdown_translator.py
- src/co_op_translator/core/llm/providers/azure/text_translator.py
- src/co_op_translator/core/llm/providers/openai/markdown_translator.py
- src/co_op_translator/core/llm/providers/openai/text_translator.py
- src/co_op_translator/core/llm/text_translator.py
- src/co_op_translator/core/project/directory_manager.py
- src/co_op_translator/core/project/project_translator.py
- src/co_op_translator/core/project/translation_manager.py
- src/co_op_translator/core/vision/image_translator.py
- src/co_op_translator/core/vision/providers/azure/image_translator.py
- tests/co_op_translator/core/llm/test_markdown_translator.py
- tests/co_op_translator/core/llm/test_text_translator.py
- tests/co_op_translator/core/project/test_directory_manager.py
- tests/co_op_translator/utils/common/test_file_utils.py
- tests/co_op_translator/utils/common/test_metadata_utils.py
- tests/co_op_translator/utils/common/test_task_utils.py
- tests/co_op_translator/utils/llm/test_markdown_utils.py
- tests/co_op_translator/utils/llm/test_text_utils.py
- tests/co_op_translator/utils/vision/test_image_utils.py
Improve code clarity, maintainability, and documentation accuracy by:
- Cleaning up test file headers and unused imports
- Updating documentation to reflect Azure AI Vision branding
- Enhancing docstrings and comments for consistency
- Removed unnecessary file/module-level docstrings and unused imports from multiple test files for brevity and clarity.
Ensured test files only import what is needed, improving readability and reducing clutter.
- Updated references from "Azure Computer Vision" to "Azure AI Vision" in documentation and guides to reflect current Azure branding and capabilities.
- Fixed broken links and improved the setup guide for Azure AI resources.
- Minor improvements to documentation formatting and accuracy.
- Standardized and clarified docstrings across core translation …
> Core, Docs: Improve code clarity, maintainability, and documentation

- README.md
- getting_started/supported-languages.md
Update supported languages table to include Burmese (Myanmar)
- Added **Burmese (Myanmar)** (`my`) to the list of supported languages:
- Updated language code table in the **README**
- Linked to Burmese README in the **Multi-Language Support** section
- Added font mapping in `font_language_mappings.yml` using `NotoSansMyanmar-Medium.ttf`
> Docs: Update supported languages table to include Burmese (Myanmar)

- translations/ja/README.md
* Untranslated "Fill in the required API keys～"
> Update README.md (Untranslated "Fill in the required API keys～")

- translations/ja/README.md
* Untranslated "Navigate to your project's root～"
> Update README.md (Untranslated "Navigate to your project's root～")

- pyproject.toml
> Update Co-op Translator version to 0.8.7

- translations/ja/README.md
* Untranslated "Execute the translate command,～"
> Update README.md (Untranslated "Execute the translate command,～")

- translations/ja/README.md
*Untranslated "Detailed Usage Guides"
> Update README.md (Untranslated "Detailed Usage Guides")

- translations/ja/README.md
* Untranslated "Requires: Local installation～"
> Update README.md (Untranslated "Requires: Local installation～")

- pyproject.toml
> Build: Update version to 0.8.8

- translations/ja/README.md
* Untranslated "Guide: [Command Line Guide]～"
* #133
> Update README.md (Untranslated "Guide: [Command Line Guide]～")

- src/co_op_translator/core/llm/markdown_evaluator.py
- src/co_op_translator/core/llm/markdown_translator.py
- src/co_op_translator/utils/llm/markdown_utils.py
- tests/co_op_translator/core/llm/test_markdown_translator.py
> Core: Remove inline code placeholders to fix partial translation issues

- translations/ja/README.md
* Untranslated "Best for: Automatically translating～")
* https://github.com/Azure/co-op-translator/blob/main/translations/ja/README.md
* #133
> Update README.md (Untranslated "Best for: Automatically translating～")

- translations/ja/getting_started/troubleshooting.md
* Untranslated "`` are added."
* https://github.com/Azure/co-op-translator/blob/main/translations/ja/getting_started/troubleshooting.md 
#133
> Update troubleshooting.md (Untranslated "`` are added.")

- translations/ja/getting_started/set-up-azure-ai.md
* Untranslated "Note"
* https://github.com/Azure/co-op-translator/blob/main/translations/ja/getting_started/set-up-azure-ai.md #
* PingMSFTDocs
> Update set-up-azure-ai.md (Untranslated "Note")

- pyproject.toml
> Build: Update version to 0.9.0

- translations/ja/getting_started/troubleshooting.md
*   Untranslated "`` are added."
*  https://github.com/Azure/co-op-translator/blob/main/translations/ja/getting_started/troubleshooting.md
*  #PingMSFTDocs
related #171
> Docs: Update troubleshooting.md (Untranslated "`` are added.")

- translations/ja/getting_started/troubleshooting.md
* Untranslated "**Solution:** Adjust～"
* https://github.com/Azure/co-op-translator/blob/main/translations/ja/getting_started/troubleshooting.md 
related #172
> Update troubleshooting.md (Untranslated "**Solution:** Adjust～")

- README.md
Update Discord Badge
Discord badge not working 
- [ x] **I have thoroughly tested my changes**: I confirm that I have run the code and manually tested all affected areas.
- [ x] **All existing tests pass**: I have run all tests and confirmed that nothing is broken.
- [x ] **I have added new tests** (if applicable): I have written tests that cover the new functionality introduced by my code changes.
- [ x] **I have followed the Co-op Translators coding conventions**: My code adheres to the style guide and coding conventions outlined in the repository.
-  [x] **I have …
> Update README.md Discord badge

- pyproject.toml
> Build: Update version to 0.10.0-pre.2

- pyproject.toml
> Build: Upgrade version to v0.10.0rc3

- pyproject.toml
> Build: Update version to v0.10.0

- pyproject.toml
> Build: Upgrade version to v0.10.3

- README.md
> Docs: Add AI Discord and Forum Links
